server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wang-wenxiangs/springcloud2022-config.git #GitHub上面的git仓库名字
          default-label: main
          username: wang-wenxiangs
          password: wang991124@
          ####搜索目录
          search-paths:
            - springcloud2022-config

      ####读取分支
      #label: master


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

#management:
#  endpoints:  # 暴露bus 接口 ，否则 更新 refresh 没用的
#    web:
#      exposure:    # expose: "*" 已过期
#        include: "*"
#  endpoint:
#    bus-refresh:
#      enabled: true
